export const DEFAULT_REFERRAL_BENEFITS = [
  {
    title: "Earn ₹1,000 on Every Loan Disbursal",
    subtitle: "Get cash rewards on every single loan disbursed by your referred partners.",
    description: "Earn rewards on every loan file! Whenever any partner you invited completes a loan disbursement for their customer, you receive cash rewards directly credited to your wallet / bank account. You earn on every disbursal, not just the first one!",
    rewardAmount: "₹1,000 / Disbursal",
    badgeText: "Every Disbursed Loan",
    gradientPreset: "teal",
    iconName: "award",
    ctaText: "Invite Partner",
    displayOrder: 1,
    isActive: true,
    terms: "Earn cash rewards on every verified partner disbursed loan file.",
  },
  {
    title: "Build Lifetime Network Earnings",
    subtitle: "Every partner joins your network permanently, generating ongoing benefits.",
    description: "Expand your partner network with DSAs, loan agents, and financial consultants. As they grow their business, your referral earnings grow with them.",
    rewardAmount: "Lifetime",
    badgeText: "Passive Growth",
    gradientPreset: "purple",
    iconName: "trending-up",
    ctaText: "Share Code",
    displayOrder: 2,
    isActive: true,
    terms: "No cap on the number of partners you can refer.",
  },
  {
    title: "Instant Verification & Fast Payouts",
    subtitle: "Transparent ledger tracking with direct bank account payouts upon approval.",
    description: "Track all your referred partners, application milestones, and earnings in real-time. Approved referral rewards are disbursed quickly without hassle.",
    rewardAmount: "Zero Delay",
    badgeText: "Direct Transfer",
    gradientPreset: "emerald",
    iconName: "wallet",
    ctaText: "View History",
    displayOrder: 3,
    isActive: true,
    terms: "Requires active partner KYC and verified bank account.",
  },
  {
    title: "Special Referral Milestone Bonuses",
    subtitle: "Unlock exclusive tier upgrades and high-value rewards as your invites disburse more.",
    description: "Reach referral milestones each month to unlock extra commission slabs, performance badges, and priority RM support.",
    rewardAmount: "Bonus Slabs",
    badgeText: "Milestone Perks",
    gradientPreset: "amber",
    iconName: "sparkles",
    ctaText: "Check Rewards",
    displayOrder: 4,
    isActive: true,
    terms: "Calculated based on monthly partner network performance.",
  },
];
